WHITE = 'white'
BLACK = 'black'
GREEN = 'green'
TABLE_GREEN = (16, 102, 58)
GOLD = (197, 160, 89)
GOLD_LIGHT = (244, 215, 94)
RED = "red"
BLUE = "blue"
DEFAULT_FONT = 'casino_font.otf'
FONT_SIZE_LARGE = 44
FONT_SIZE_SMALL = 36
BORDER_RADIUS = 8
RESULTS = ['', 'Player busted!', 'Player wins!', 'Dealer wins!', 'Tie game!']
RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']